apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key-test
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: cloudflare-api-key-test
    creationPolicy: Owner
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: cloudflare-api-key
        property: CF_API_KEY
    - secretKey: CF_API_EMAIL
      remoteRef:
        key: cloudflare-api-key
        property: CF_API_EMAIL