apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: cloudflare-api-key
        property: CF_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CF_API_EMAIL
      remoteRef:
        key: cloudflare-api-key
        property: CF_API_EMAIL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None