controllers:
  minio:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: quay.io/minio/minio
          tag: RELEASE.2024-07-16T23-46-41Z
        args:
          - server
          - /data
          - --console-address
          - :9001
        probes:
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
          liveness:
            enabled: true
          readiness:
            enabled: true
        env:
          MINIO_UPDATE: "off"
          MINIO_BROWSER_REDIRECT_URL: https://minio.integratn.tech
          MINIO_SERVER_URL: https://s3.integratn.tech
          # MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring-system.svc.cluster.local:9090
          MINIO_PROMETHEUS_JOB_ID: minio
          MINIO_PROMETHEUS_AUTH_TYPE: public
        envFrom:
          - secretRef:
              name: minio-secret
service:
  main:
    controller: minio
    ports:
      http:
        port: 9001
      api:
        port: 9000
ingress:
  main:
    enabled: true
    className: nginx
    hosts:
      - host: &host minio.integratn.tech
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: minio-prod-tls
  s3:
    enabled: true
    className: nginx
    hosts:
      - host: &host s3.integratn.tech
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: api
    tls:
      - hosts:
          - *host
        secretName: s3-prod-tls
serviceMonitor:
  main:
    serviceName: minio
    enabled: true
    endpoints:
      - port: api
        scheme: http
        path: /minio/v2/metrics/cluster
        interval: 1m
        scrapeTimeout: 10s
persistence:
  config:
    enabled: true
    existingClaim: minio-nfs
    globalMounts:
      - path: /data