apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-cluster-workloads
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: 'git@github.com:jamesAtIntegratnIO/gitops-homelab.git'
        revision: 'main'
        directories:
        - path: 'gitops/workloads/monitoring-cluster/*'
        - path: 'gitops/workloads/monitoring-cluster/exclude'
          exclude: true
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: 'git@github.com:jamesAtIntegratnIO/gitops-homelab.git'
        targetRevision: 'main'
        path: '{{.path.path}}'
      destination:
        namespace: '{{.path.basenameNormalized}}'
        name: 'monitoring-cluster'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true