apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-cluster-workloads
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: 'git@github.com:jamesAtIntegratnIO/gitops-homelab.git'
        revision: 'main'
        files:
        - path: 'gitops/workloads/monitoring-cluster/*/config.json'
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      sources:
        - chart: '{{.chartName}}'
          repoURL: '{{.chartRepoURL}}'
          targetRevision: '{{.chartRevision}}'
          helm:
            releaseName: '{{.path.basenameNormalized}}'
            ignoreMissingValueFiles: true
            valueFiles: 
              - $values/{{.path.path}}/manifests/values.yaml
        - repoURL: 'git@github.com:jamesAtIntegratnIO/gitops-homelab.git'
          targetRevision: 'main'
          path: '{{.path.path}}/manifests'
          ref: values

      destination:
        namespace: '{{.path.basenameNormalized}}'
        name: 'monitoring-cluster'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true