apiVersion: v1
kind: Secret
metadata:
  name: media-cluster-prometheus-additional-scrape-configs
  namespace: monitoring
stringData:
  additional-scrape-configs.yaml: |
    - job_name: 'kubernetes'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_prometheus]
          action: keep
          regex: media-cluster

        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true

        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)

        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: (.+)

        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace

        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod

        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container

        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          target_label: app

        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app

        - source_labels: [__meta_kubernetes_pod_label_team]
          target_label: team

        - source_labels: [__meta_kubernetes_node_name]
          target_label: node

        - target_label: cluster
          replacement: media-cluster
