
apiVersion: job.min.io/v1alpha1
kind: MinIOJob
metadata:
  name: minio-user-creation-job
  namespace: minio-tenant
spec:
  serviceAccountName: mc-job-sa
  tenant:
    name: default
    namespace: minio-tenant
  commands:
    - name: add-admin-user
      op: admin/user/add
      args:
        user: $(USERNAME)
        password: $(PASSWORD)
      envFrom:
        - secretRef:
            name: minio-admin-user
    - name: admin-policy-create
      op: admin/policy/create
      args:
        name: admin-access
        policy: /temp/policy.json
      volumeMounts:
        - name: policy
          mountPath: /temp
      volumes:
        - name: policy
          configMap:
            name: mc-admin-policy
            items:
              - key: policy.json
                path: policy.json
    - name: admin-policy-attach
      op: admin/policy/attach
      dependsOn:
        - add-admin-user
        - admin-policy-create
      args:
        user: $(USERNAME)
        policy: admin-access
      envFrom:
        - secretRef:
            name: minio-admin-user
