apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-job-sa
automountServiceAccountToken: true

---
apiVersion: sts.min.io/v1alpha1
kind: PolicyBinding
metadata:
  name: mc-job-binding
spec:
  application:
    serviceaccount: mc-job-sa
    namespace: minio-tenant
  policies:
    - consoleAdmin
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: minio-tenant
 name: mc-job-sa-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: mc-job-sa-secret-reader-binding
 namespace: minio-tenant
subjects:
- kind: ServiceAccount
  name: mc-job-sa
  namespace: minio-tenant
roleRef:
 kind: Role
 name: mc-job-sa-secret-reader
 apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-admin-policy
data:
  policy.json: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "admin:*"
                ]
            }
        ]
    }
---
apiVersion: job.min.io/v1alpha1
kind: MinIOJob
metadata:
  name: minio-user-creation-job
  namespace: minio-tenant
spec:
  serviceAccountName: mc-job-sa
  tenant: 
    name: default
    namespace: minio-tenant
  commands:
    - name: add-admin-user
      op: admin/user/add
      args:
        user: ${USERNAME}
        password: ${PASSWORD}
      envFrom:
        - secretRef:
            name: minio-tenant-user
    - name: admin-policy-create
      op: admin/policy/create
      args:
        name: admin-access
        policy: /temp/policy.json
      volumeMounts:
        - name: policy
          mountPath: /temp
      volumes:
        - name: policy
          configMap:
            name: mc-admin-policy
            items:
              - key: policy.json
                path: policy.json
    - name: admin-policy-attach
      op: admin/policy/attach
      dependsOn:
        - add-admin-user
        - admin-policy-create
      args:
        user: ${USERNAME}
        policy: admin-access
      envFrom:
        - secretRef:
            name: minio-tenant-user
