resources:
- onepasswordItems.yaml
- minio-jobs-sa.yaml
- admin-policy-cm.yaml
- admin-user-miniojob.yaml
- logs-writer-policy-cm.yaml
- logs-writer-miniojob.yaml
- thanos-writer-policy-cm.yaml
- thanos-writer-miniojob.yaml