apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-logs-writer-policy
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket",
            "s3:PutObject",
            "s3:GetObject",
            "s3:DeleteObject"
          ],
          "Resource": [
            "arn:aws:s3:::logs",
            "arn:aws:s3:::logs/*"
          ]
        }
      ]
    }