apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-job-sa
automountServiceAccountToken: true

---
apiVersion: sts.min.io/v1alpha1
kind: PolicyBinding
metadata:
  name: mc-job-binding
spec:
  application:
    serviceaccount: mc-job-sa
    namespace: minio-tenant
  policies:
    - consoleAdmin
---