secrets:
  name: &name default-tenant-config
tenant:
  name: default
  configuration: 
    name: *name
  pools:
  - servers: 1
    name: default-pool
    volumesPerServer: 1
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
    storageClassName: nfs-client
    size: 50Gi
    containerSecurityContext:
      runAsUser: 99
      runAsGroup: 100
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

  env: 
    - name: MINIO_DOMAIN
      value: "minio.integratn.tech"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://console.integratn.tech"
    - name: MINIO_SERVER_URL
      value: "https://minio.integratn.tech"
  exposeServices:
    console: false
    minio: false
  buckets:
    - name: default-bucket
      region: us-home-1
      objectLock: false
    - name: terraform-state
      region: us-home-1
      objectLock: true
    - name: logs
      region: us-home-1
      objectLock: false
    - name: thanos
      region: us-home-1
      objectLock: false
  features:
    bucketDNS: true
  
ingress:
  api:
    enabled: true
    ingressClassName: "nginx"
    labels: { }
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      reloader.stakater.com/auto: "true"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/server-snippet: |
        client_max_body_size 0;
      nginx.ingress.kubernetes.io/configuration-snippet: |
        chunked_transfer_encoding off;
    tls: 
      - hosts:
          - &host minio.integratn.tech
          - "*.minio.integratn.tech"
        secretName: minio-tls
    host: *host
    path: /
    pathType: Prefix
  console:
    enabled: true
    ingressClassName: "nginx"
    labels: { }
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      reloader.stakater.com/auto: "true"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/server-snippet: |
    tls: 
      - hosts:
          - &host console.integratn.tech

        secretName: minio-prod-tls
    host: *host
    path: /
    pathType: Prefix