apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-media-repository
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: tensure-argocd-platform-appsets-repository
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: name
      remoteRef:
        key: argocd-repo-creds-tensure-argocd-private-details
        property: name
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
    - secretKey: url
      remoteRef:
        key: argocd-repo-creds-tensure-argocd-private-details
        property: url
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
  dataFrom:
    - extract: 
        key: argocd-repo-creds-gitops-homelab-private
        decodingStrategy: Auto
        conversionStrategy: Default
        metadataPolicy: None