apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-argocd-image-updater-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: argocd-image-updater-secret
    creationPolicy: Owner

  data:
    - secretKey: argocd.token
      remoteRef:
        key: argocd-image-updater-secret
        property: argocd.token
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
    - secretKey: dockerhub
      remoteRef:
        key: argocd-image-updater-secret
        property: dockerhub
        decodingStrategy: None
        conversionStrategy: Default
        metadataPolicy: None
