ingress:
  hosts:
    - host: headlamp.cp.integratn.tech
      paths:
        - path: /
          type: ImplementationSpecific
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.cp.integratn.tech