apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: media-cluster
  namespace: k0s-media-cluster
spec:
  version: v1.32.4-k0s.0
  persistence:
    type: persistentVolumeClaim
    persistentVolumeClaim:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nfs-client
  service:
    type: NodePort
  etcd:
    persistence:
      storageClass: nfs-client
  # k0sConfig:
  #   apiVersion: k0s.k0sproject.io/v1beta1
  #   kind: Cluster
  #   spec:
  #     storage:
  #       type: etcd
  #     network:
  #       podCIDR: 10.243.0.0/16
  #       serviceCIDR: 10.112.0.0/12
  #       provider: calico
  #       calico:
  #         mode: vxlan
  #         vxlanPort: 4789
  #         vxlanVNI: 4096
  #         mtu: 1450
  #         wireguard: false
  #         flexVolumeDriverPath: /usr/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds
  #         withWindowsNodes: false
  #         overlay: Always  
  #     telemetry:
  #       enabled: false
  #     images:
  #       calico:
  #         cni:
  #           image: quay.io/k0sproject/calico-cni
  #           version: v3.29.3-0
  #         kubecontrollers:
  #           image: quay.io/k0sproject/calico-kube-controllers
  #           version: v3.29.3-0
  #         node:
  #           image: quay.io/k0sproject/calico-node
  #           version: v3.29.3-0
  #       coredns:
  #         image: quay.io/k0sproject/coredns
  #         version: 1.12.0
  #       konnectivity:
  #         image: quay.io/k0sproject/apiserver-network-proxy-agent
  #         version: v0.31.0
  #       kubeproxy:
  #         image: quay.io/k0sproject/kube-proxy
  #         version: v1.32.4
  #       kuberouter:
  #         cni:
  #           image: quay.io/k0sproject/kube-router
  #           version: v2.4.1-iptables1.8.9-0
  #         cniInstaller:
  #           image: quay.io/k0sproject/cni-node
  #           version: 1.3.0-k0s.0
  #       metricsserver:
  #         image: registry.k8s.io/metrics-server/metrics-server
  #         version: v0.7.2
  #       pause:
  #         image: registry.k8s.io/pause
  #         version: "3.9"
  #       pushgateway:
  #         image: quay.io/k0sproject/pushgateway-ttl
  #         version: 1.4.0-k0s.0
  #       default_pull_policy: IfNotPresent
  #     konnectivity:
  #       agentPort: 8132
  #       adminPort: 8133

