namespace: k0s-media-cluster
resources:
  - namespace.yaml
  - controlplane.yaml
  - remote-cluster.yaml
  - media-cluster.yaml
  - sshkey-secret.yaml
  - media-cluster-worker1.yaml
  - media-cluster-worker2.yaml