apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name:  k0s-media-worker2
  namespace: k0s-media-cluster
spec:
  clusterName: media-cluster
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: k0s-media-worker2
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: k0s-media-worker2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: k0s-media-worker2
  namespace: k0s-media-cluster
spec:
  version: v1.32.4-k0s.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: k0s-media-worker2
  namespace: k0s-media-cluster
spec:
  address: 10.0.6.102
  port: 22
  user: root
  sshKeyRef:
    # This defines which SSH key to use for connecting to the machine. The Secret needs to have key 'value' with the SSH private key in it.
    name: media-cluster-ssh-key