---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachineTemplate
metadata:
  name: media-cluster-remote-machine-template
  namespace: k0smotron
spec:
  template:
    spec:
      pool: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: k0s-media-worker1
  namespace: k0smotron
spec:
  pool: default
  machine:
    address: 10.0.6.101
    port: 22
    user: root
    sshKeyRef:
      name: media-cluster-ssh-key
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: k0s-media-worker2
  namespace: k0smotron
spec:
  pool: default
  machine:
    address: 10.0.6.102
    port: 22
    user: root
    sshKeyRef:
      name: media-cluster-ssh-key
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: k0s-media-worker3
  namespace: k0smotron
spec:
  pool: default
  machine:
    address: 10.0.6.103
    port: 22
    user: root
    sshKeyRef:
      name: media-cluster-ssh-key