apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-store
spec:
  provider:
    onepassword:
      connectHost: https://connect.integratn.tech
      vaults:
        homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: eso-onepassword-token
            namespace: external-secrets
            key: token